package com.taxengine.facts.domain.enums;

public enum FactType {
    SALARY_INCOME_FACT,
    BUSINESS_INCOME_FACT,
    FREELANCE_INCOME_FACT,
    RENTAL_INCOME_FACT,
    INTEREST_INCOME_FACT,
    DIVIDEND_INCOME_FACT,
    CAPITAL_GAIN_TRANSACTION_FACT,
    CRYPTO_TRANSACTION_FACT,
    FOREIGN_INCOME_FACT,
    OTHER_INCOME_FACT,

    RENT_PAYMENT_FACT,
    INSURANCE_PREMIUM_FACT,
    MEDICAL_EXPENSE_FACT,
    EDUCATION_EXPENSE_FACT,
    DONATION_FACT,
    HOME_LOAN_INTEREST_FACT,

    PROVIDENT_FUND_CONTRIBUTION_FACT,
    NPS_CONTRIBUTION_FACT,
    ELSS_INVESTMENT_FACT,
    LIFE_INSURANCE_PREMIUM_FACT,

    CAPITAL_LOSS_FACT,
    BUSINESS_LOSS_FACT,
    LOSS_CARRY_FORWARD_FACT,

    TDS_FACT,
    ADVANCE_TAX_PAYMENT_FACT,
    SELF_ASSESSMENT_TAX_FACT,

    FOREIGN_ASSET_FACT,
    DIRECTOR_IN_COMPANY_FACT,
    PROPERTY_OWNERSHIP_FACT
}
